### ISSUE TITLE
Weird error

### ISSUE THREAD

**Issue by benzBullz** [jackprogramsjp/Roblopy#3]
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    print(Assets.user_has_asset(userid,assetid))
  File "/var/mobile/Containers/Data/Application/BCB9FE4C-414B-473A-9817-4847A4FD7876/Documents/site-packages3/roblopy/assets.py", line 54, in user_has_asset
    "https://api.roblox.com/Ownership/HasAsset?userId=" + str(user_id) + "&assetId=" + str(asset_id)).json()
  File "/var/mobile/Containers/Data/Application/BCB9FE4C-414B-473A-9817-4847A4FD7876/Documents/site-packages3/roblopy/utils/request.py", line 7, in get
    if "errorMessage" in response.json():
TypeError: argument of type 'bool' is not iterable

**Comment by jackprogramsjp** [comment]
Thank you for this issue! I didn't even realize that, it looks like I haven't tested the whole package good enough. I will update the package, and now I have figured out how to solve this issue you have got. Thank you very much for telling me this issue!

Currently I'm on vacation, so it's a bit hard for me to update this package currently, therefore I'll try my best to fix this ASAP.

**Comment by benzBullz** [comment]
Thank you for the reply. I suggest you check the “get_avatar_image()”
method also.

**Comment by jackprogramsjp** [comment]
Yes, I actually know the "get_avatar_image()" error as well! Thanks for the reminder! I'll get those fixed ASAP!

**Comment by jackprogramsjp** [comment]
Alright. Just released Version 5.1, so now "get_avatar_image()" and "user_has_asset()" should be fixed. Enjoy using Roblopy 👍

**Comment by benzBullz** [comment]
Thank you! :)

**Comment by jackprogramsjp** [comment]
Yeah! You're welcome!
